language: python
python:
  - 3.6
  - 3.7
addons:
  apt:
    packages:
      - kyototycoon
      - libkyotocabinet-dev
      - libkyototycoon-dev
      - libmemcached-dev
install:
  - pip install cython gevent msgpack-python
  - pip install greendb peewee pylibmc pymemcache redis ukt
  - wget http://fallabs.com/kyotocabinet/pythonpkg/kyotocabinet-python-1.22.tar.gz
  - tar xzf kyotocabinet-python-1.22.tar.gz
  - cd kyotocabinet-python-1.22 && python setup.py install && cd ../
services:
  - memcached
  - redis-server
script:
  - ktserver&
  - greendb.py&
  - python tests.py
  - pkill ktserver
  - pkill greendb.py
