language: python
python:
  - 3.6
  - 3.7
addons:
  apt:
    packages:
      - kyototycoon
      - libkyototycoon-dev
      - libmemcached-dev
install:
  - pip install cython gevent msgpack-python
  - pip install greendb pylibmc pymemcache redis ukt
services:
  - memcached
  - redis-server
script:
  - ktserver&
  - greendb.py&
  - python tests.py
  - pkill ktserver
  - pkill greendb.py
